title: "Shar rGya mTsho"
author: "Hwigkim"
description: "Tibetology & Sinology"
url: ""

# Jekyll Markdown Configuration
markdown: Pandoc
pandoc:
  extensions: [
    "--lua-filter=pandoc-filters/pandoc-sidenote.lua"
  ]

# Jekyll Plugins
plugins:
  - jekyll-pandoc

# Exclusion list
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/

# Cusdis Comments Configuration
# Cusdis dashboard(https://cusdis.com)에서 발급받은 App ID를 여기에 입력하세요.
cusdis_app_id: "017b3843-5f7a-44df-ab44-d8db2a1e2dad"
